// src/app/layout.tsx
import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DashboardWrapper from "./dashboardWrapper";
import AuthProvider from "./authProvider";
import I18nClientWrapper from "./I18nClientWrapper"; // Import the client wrapper


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "MYSTOCK",
  description: "Generated by Fred_Soma",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Wrap the parts that need client-side context with I18nClientWrapper */}
        <I18nClientWrapper>
          <AuthProvider>
            <DashboardWrapper>{children}</DashboardWrapper>
          </AuthProvider>
        </I18nClientWrapper>
      </body>
    </html>
  );
}
